apiVersion: v2
name: nats-jetstream-manager
description: >-
  A Helm chart for NATS JetStream Manager - a web UI for managing NATS JetStream
  clusters
type: application
version: 1.11.3
appVersion: 1.11.3
keywords:
  - nats
  - jetstream
  - streaming
  - messaging
maintainers:
  - name: ncbernar
