{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nats-jetstream-manager.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nats-jetstream-manager.frontend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.frontend.tls }}
  tls:
    {{- toYaml .Values.ingress.frontend.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.frontend.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.frontend.path }}
            pathType: {{ .Values.ingress.frontend.pathType }}
            backend:
              service:
                name: {{ include "nats-jetstream-manager.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nats-jetstream-manager.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nats-jetstream-manager.backend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.backend.tls }}
  tls:
    {{- toYaml .Values.ingress.backend.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.backend.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.backend.path }}
            pathType: {{ .Values.ingress.backend.pathType }}
            backend:
              service:
                name: {{ include "nats-jetstream-manager.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
{{- end }}
