{{- if not .Values.backend.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nats-jetstream-manager.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nats-jetstream-manager.backend.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{- if .Values.backend.secrets.adminToken }}
  ADMIN_TOKEN: {{ .Values.backend.secrets.adminToken | quote }}
  {{- end }}
  {{- if .Values.backend.secrets.viewerToken }}
  VIEWER_TOKEN: {{ .Values.backend.secrets.viewerToken | quote }}
  {{- end }}
  {{- if .Values.backend.secrets.smtpPassword }}
  SMTP_PASSWORD: {{ .Values.backend.secrets.smtpPassword | quote }}
  {{- end }}
  {{- if .Values.backend.secrets.databasePassword }}
  DATABASE_PASSWORD: {{ .Values.backend.secrets.databasePassword | quote }}
  {{- end }}
{{- end }}
