{{- if not .Values.backend.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nats-jetstream-manager.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nats-jetstream-manager.backend.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
{{- if .Values.backend.secrets.databasePassword }}
stringData:
  DATABASE_PASSWORD: {{ .Values.backend.secrets.databasePassword | quote }}
{{- else }}
stringData: {}
{{- end }}
{{- end }}
