apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nats-jetstream-manager.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nats-jetstream-manager.backend.labels" . | nindent 4 }}
data:
  NATS_URL: {{ .Values.backend.config.natsUrl | quote }}
  LOG_LEVEL: {{ .Values.backend.config.logLevel | quote }}
  CORS_ORIGINS: {{ include "nats-jetstream-manager.corsOrigins" . | quote }}
  {{- range $key, $value := .Values.backend.config.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
